# Generated by Django 2.2.4 on 2019-08-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_hostel_course'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hostel.Hostel'),
        ),
    ]
