# Generated by Django 2.2.4 on 2019-08-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, to='course.Course'),
        ),
    ]
